### ISSUE TITLE
wthat does **a prebuilt module** refer to ?

### ISSUE THREAD

**Issue by vipzrx** [abforce/xposed_art_n#14]
Create a prebuilt module that copies `XposedBridge.jar` to `system/framework`, or manually copy it and run `make snod` to include it in the `system.img`.

in above , wthat does **a prebuilt module** refer to ?

**Comment by abforce** [comment]
In AOSP source tree, prebuilt modules are placed in `prebuilts/` directory. In this case you can create a module in `prebuilts/misc/common/XposedBridge` that copies that jar file. Note that, that's not madatory whatsoever. It just turns the make process to be more automatic than manual. You *can* skip this step and copy that jar file manually. Just make sure after copying you must issue `make snod` so that `system.img` gets updated.
